package com.fizzware.dramaticdoors.init.compat;

import com.fizzware.dramaticdoors.DDNames;
import com.fizzware.dramaticdoors.DramaticDoors;
import com.fizzware.dramaticdoors.blocks.TallDoorBlock;
import com.fizzware.dramaticdoors.blocks.TallSlidingDoorBlock;
import com.fizzware.dramaticdoors.blocks.TallStableDoorBlock;
import com.fizzware.dramaticdoors.init.DDBlocks;
import com.fizzware.dramaticdoors.init.DDItems;
import com.fizzware.dramaticdoors.items.TallDoorItem;

import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegisterEvent;

public class DDMacawsDoorsRegistry
{
	@SubscribeEvent
	public static void register(RegisterEvent event) {
		event.register(ForgeRegistries.Keys.BLOCKS, helper -> {
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_STORE), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "store_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SLIDING_GLASS), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "sliding_glass_door"))));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JAIL), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "jail_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_METAL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "metal_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_METAL_HOSPITAL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "metal_hospital_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_METAL_REINFORCED), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "metal_reinforced_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_METAL_WARNING), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "metal_warning_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_METAL_WINDOWED), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "metal_windowed_door"))));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_BARN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "oak_barn_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_BARN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "spruce_barn_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_BARN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "birch_barn_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_BARN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "jungle_barn_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_BARN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_barn_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_BARN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "dark_oak_barn_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_BARN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_barn_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_BARN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "bamboo_barn_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_BARN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "crimson_barn_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_BARN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "warped_barn_door"))));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_BARN_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "oak_barn_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_BARN_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "spruce_barn_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_BARN_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "birch_barn_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_BARN_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "jungle_barn_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_BARN_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "acacia_barn_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_BARN_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "dark_oak_barn_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_BARN_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_barn_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_BARN_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "bamboo_barn_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_BARN_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "crimson_barn_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_BARN_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "warped_barn_glass_door"))));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_STABLE), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "oak_stable_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_STABLE), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "spruce_stable_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_STABLE), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "birch_stable_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_STABLE), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "jungle_stable_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_STABLE), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_stable_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_STABLE), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "dark_oak_stable_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_STABLE), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_stable_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_STABLE), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "bamboo_stable_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_STABLE), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "crimson_stable_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_STABLE), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "warped_stable_door"))));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_STABLE_HEAD), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "oak_stable_head_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_STABLE_HEAD), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "spruce_stable_head_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_STABLE_HEAD), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "birch_stable_head_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_STABLE_HEAD), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "jungle_stable_head_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_STABLE_HEAD), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_stable_head_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_STABLE_HEAD), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "dark_oak_stable_head_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_STABLE_HEAD), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_stable_head_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_STABLE_HEAD), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "bamboo_stable_head_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_STABLE_HEAD), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "crimson_stable_head_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_STABLE_HEAD), new TallStableDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "warped_stable_head_door"))));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_BARK_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "oak_bark_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_BARK_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "spruce_bark_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_BARK_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "birch_bark_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_BARK_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "jungle_bark_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_BARK_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_bark_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_BARK_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "dark_oak_bark_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_BARK_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_bark_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_BARK_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "bamboo_bark_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_STEM_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "crimson_stem_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_STEM_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "warped_stem_glass_door"))));
	
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "oak_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "spruce_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "birch_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "jungle_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "dark_oak_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "bamboo_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "crimson_glass_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_GLASS), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "warped_glass_door"))));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_MODERN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "oak_modern_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_MODERN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "spruce_modern_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_MODERN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "birch_modern_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_MODERN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "jungle_modern_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_MODERN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_modern_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_MODERN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "dark_oak_modern_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_MODERN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_modern_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_MODERN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "bamboo_modern_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_MODERN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "crimson_modern_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_MODERN), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "warped_modern_door"))));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_JAPANESE), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "oak_japanese_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_JAPANESE), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "spruce_japanese_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_JAPANESE), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "birch_japanese_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_JAPANESE), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "jungle_japanese_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_JAPANESE), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_japanese_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_JAPANESE), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "dark_oak_japanese_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_JAPANESE), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_japanese_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_JAPANESE), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "bamboo_japanese_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_JAPANESE), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "crimson_japanese_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_JAPANESE), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "warped_japanese_door"))));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_JAPANESE2), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "oak_japanese2_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_JAPANESE2), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "spruce_japanese2_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_JAPANESE2), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "birch_japanese2_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_JAPANESE2), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "jungle_japanese2_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_JAPANESE2), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_japanese2_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_JAPANESE2), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "dark_oak_japanese2_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_JAPANESE2), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_japanese2_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_JAPANESE2), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "bamboo_japanese2_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_JAPANESE2), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "crimson_japanese2_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_JAPANESE2), new TallSlidingDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "warped_japanese2_door"))));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_CLASSIC), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "spruce_classic_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_CLASSIC), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "birch_classic_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_CLASSIC), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "jungle_classic_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_CLASSIC), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_classic_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_CLASSIC), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "dark_oak_classic_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_CLASSIC), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_classic_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_CLASSIC), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "bamboo_classic_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_CLASSIC), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "crimson_classic_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_CLASSIC), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "warped_classic_door"))));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_COTTAGE), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "oak_cottage_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_COTTAGE), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "birch_cottage_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_COTTAGE), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "jungle_cottage_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_COTTAGE), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_cottage_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_COTTAGE), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "dark_oak_cottage_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_COTTAGE), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_cottage_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_COTTAGE), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "bamboo_cottage_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_COTTAGE), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "crimson_cottage_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_COTTAGE), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "warped_cottage_door"))));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_PAPER), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "oak_paper_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_PAPER), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "spruce_paper_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_PAPER), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "jungle_paper_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_PAPER), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_paper_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_PAPER), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "dark_oak_paper_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_PAPER), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_paper_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_PAPER), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "bamboo_paper_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_PAPER), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "crimson_paper_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_PAPER), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "warped_paper_door"))));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_BEACH), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "oak_beach_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_BEACH), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "spruce_beach_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_BEACH), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "birch_beach_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_BEACH), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_beach_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_BEACH), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "dark_oak_beach_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_BEACH), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_beach_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_BEACH), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "bamboo_beach_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_BEACH), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "crimson_beach_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_BEACH), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "warped_beach_door"))));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_TROPICAL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "oak_tropical_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_TROPICAL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "spruce_tropical_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_TROPICAL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "birch_tropical_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_TROPICAL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "jungle_tropical_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_TROPICAL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "dark_oak_tropical_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_TROPICAL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_tropical_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_TROPICAL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "bamboo_tropical_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_TROPICAL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "crimson_tropical_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_TROPICAL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "warped_tropical_door"))));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_FOUR_PANEL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "oak_four_panel_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_FOUR_PANEL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "spruce_four_panel_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_FOUR_PANEL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "birch_four_panel_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_FOUR_PANEL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "jungle_four_panel_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_FOUR_PANEL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_four_panel_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_FOUR_PANEL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_four_panel_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_FOUR_PANEL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "bamboo_four_panel_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_FOUR_PANEL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "crimson_four_panel_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_FOUR_PANEL), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "warped_four_panel_door"))));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_SWAMP), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "oak_swamp_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_SWAMP), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "spruce_swamp_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_SWAMP), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "birch_swamp_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_SWAMP), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "jungle_swamp_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_SWAMP), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_swamp_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_SWAMP), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "dark_oak_swamp_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_SWAMP), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "bamboo_swamp_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_SWAMP), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "crimson_swamp_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_SWAMP), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "warped_swamp_door"))));
	
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_BAMBOO), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "oak_bamboo_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_BAMBOO), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "spruce_bamboo_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_BAMBOO), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "birch_bamboo_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_BAMBOO), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "jungle_bamboo_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_BAMBOO), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_bamboo_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_BAMBOO), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "dark_oak_bamboo_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_BAMBOO), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_bamboo_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_BAMBOO), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "crimson_bamboo_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_BAMBOO), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "warped_bamboo_door"))));
	
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_NETHER), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "oak_nether_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_NETHER), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "spruce_nether_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_NETHER), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "birch_nether_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_NETHER), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "jungle_nether_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_NETHER), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_nether_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_NETHER), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "dark_oak_nether_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_NETHER), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_nether_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_NETHER), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "bamboo_nether_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_NETHER), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "warped_nether_door"))));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_MYSTIC), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "oak_mystic_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_MYSTIC), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "spruce_mystic_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_MYSTIC), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "birch_mystic_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_MYSTIC), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "jungle_mystic_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_MYSTIC), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_mystic_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_MYSTIC), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "mangrove_mystic_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_MYSTIC), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "dark_oak_mystic_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_MYSTIC), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "bamboo_mystic_door"))));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_MYSTIC), new TallDoorBlock(DDBlocks.getBlockByKey(new ResourceLocation("mcwdoors", "crimson_mystic_door"))));

		});
		event.register(ForgeRegistries.Keys.ITEMS, helper -> {
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_STORE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_STORE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SLIDING_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SLIDING_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));    

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JAIL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JAIL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_METAL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_METAL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_METAL_HOSPITAL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_METAL_HOSPITAL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_METAL_REINFORCED), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_METAL_REINFORCED)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_METAL_WARNING), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_METAL_WARNING)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_METAL_WINDOWED), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_METAL_WINDOWED)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_BARN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_BARN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_BARN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_BARN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_BARN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_BARN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_BARN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_BARN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_BARN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_BARN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_BARN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_BARN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_BARN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_BARN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_BARN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_BARN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_BARN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_BARN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_BARN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_BARN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_BARN_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_BARN_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_BARN_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_BARN_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_BARN_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_BARN_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_BARN_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_BARN_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_BARN_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_BARN_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_BARN_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_BARN_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_BARN_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_BARN_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_BARN_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_BARN_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_BARN_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_BARN_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_BARN_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_BARN_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_STABLE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_STABLE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_STABLE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_STABLE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_STABLE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_STABLE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_STABLE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_STABLE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_STABLE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_STABLE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_STABLE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_STABLE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_STABLE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_STABLE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_STABLE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_STABLE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_STABLE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_STABLE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_STABLE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_STABLE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_STABLE_HEAD), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_STABLE_HEAD)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_STABLE_HEAD), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_STABLE_HEAD)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_STABLE_HEAD), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_STABLE_HEAD)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_STABLE_HEAD), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_STABLE_HEAD)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_STABLE_HEAD), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_STABLE_HEAD)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_STABLE_HEAD), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_STABLE_HEAD)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_STABLE_HEAD), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_STABLE_HEAD)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_STABLE_HEAD), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_STABLE_HEAD)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_STABLE_HEAD), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_STABLE_HEAD)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_STABLE_HEAD), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_STABLE_HEAD)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_BARK_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_BARK_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_BARK_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_BARK_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_BARK_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_BARK_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_BARK_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_BARK_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_BARK_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_BARK_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_BARK_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_BARK_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_BARK_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_BARK_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_BARK_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_BARK_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_STEM_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_STEM_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_STEM_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_STEM_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_GLASS), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_GLASS)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
    
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_MODERN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_MODERN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_MODERN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_MODERN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_MODERN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_MODERN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_MODERN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_MODERN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_MODERN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_MODERN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_MODERN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_MODERN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_MODERN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_MODERN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_MODERN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_MODERN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_MODERN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_MODERN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_MODERN), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_MODERN)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_JAPANESE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_JAPANESE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_JAPANESE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_JAPANESE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_JAPANESE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_JAPANESE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_JAPANESE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_JAPANESE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_JAPANESE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_JAPANESE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_JAPANESE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_JAPANESE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_JAPANESE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_JAPANESE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_JAPANESE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_JAPANESE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_JAPANESE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_JAPANESE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_JAPANESE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_JAPANESE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_JAPANESE2), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_JAPANESE2)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_JAPANESE2), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_JAPANESE2)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_JAPANESE2), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_JAPANESE2)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_JAPANESE2), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_JAPANESE2)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_JAPANESE2), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_JAPANESE2)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_JAPANESE2), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_JAPANESE2)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_JAPANESE2), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_JAPANESE2)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_JAPANESE2), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_JAPANESE2)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_JAPANESE2), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_JAPANESE2)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_JAPANESE2), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_JAPANESE2)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_CLASSIC), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_CLASSIC)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_CLASSIC), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_CLASSIC)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_CLASSIC), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_CLASSIC)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_CLASSIC), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_CLASSIC)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_CLASSIC), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_CLASSIC)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_CLASSIC), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_CLASSIC)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_CLASSIC), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_CLASSIC)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_CLASSIC), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_CLASSIC)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_CLASSIC), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_CLASSIC)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_COTTAGE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_COTTAGE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_COTTAGE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_COTTAGE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_COTTAGE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_COTTAGE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_COTTAGE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_COTTAGE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_COTTAGE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_COTTAGE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_COTTAGE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_COTTAGE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_COTTAGE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_COTTAGE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_COTTAGE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_COTTAGE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_COTTAGE), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_COTTAGE)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_PAPER), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_PAPER)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_PAPER), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_PAPER)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_PAPER), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_PAPER)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_PAPER), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_PAPER)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_PAPER), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_PAPER)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_PAPER), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_PAPER)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_PAPER), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_PAPER)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_PAPER), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_PAPER)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_PAPER), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_PAPER)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_BEACH), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_BEACH)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_BEACH), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_BEACH)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_BEACH), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_BEACH)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_BEACH), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_BEACH)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_BEACH), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_BEACH)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_BEACH), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_BEACH)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_BEACH), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_BEACH)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_BEACH), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_BEACH)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_BEACH), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_BEACH)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_TROPICAL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_TROPICAL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_TROPICAL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_TROPICAL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_TROPICAL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_TROPICAL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_TROPICAL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_TROPICAL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_TROPICAL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_TROPICAL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_TROPICAL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_TROPICAL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_TROPICAL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_TROPICAL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_TROPICAL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_TROPICAL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_TROPICAL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_TROPICAL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_FOUR_PANEL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_FOUR_PANEL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_FOUR_PANEL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_FOUR_PANEL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_FOUR_PANEL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_FOUR_PANEL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_FOUR_PANEL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_FOUR_PANEL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_FOUR_PANEL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_FOUR_PANEL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_FOUR_PANEL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_FOUR_PANEL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_FOUR_PANEL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_FOUR_PANEL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_FOUR_PANEL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_FOUR_PANEL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_FOUR_PANEL), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_FOUR_PANEL)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_SWAMP), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_SWAMP)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_SWAMP), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_SWAMP)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_SWAMP), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_SWAMP)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_SWAMP), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_SWAMP)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_SWAMP), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_SWAMP)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_SWAMP), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_SWAMP)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_SWAMP), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_SWAMP)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_SWAMP), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_SWAMP)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_SWAMP), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_SWAMP)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
    
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_BAMBOO), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_BAMBOO)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_BAMBOO), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_BAMBOO)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_BAMBOO), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_BAMBOO)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_BAMBOO), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_BAMBOO)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_BAMBOO), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_BAMBOO)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_BAMBOO), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_BAMBOO)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_BAMBOO), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_BAMBOO)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_BAMBOO), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_BAMBOO)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_BAMBOO), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_BAMBOO)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
    
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_NETHER), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_NETHER)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_NETHER), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_NETHER)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_NETHER), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_NETHER)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_NETHER), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_NETHER)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_NETHER), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_NETHER)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_NETHER), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_NETHER)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_NETHER), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_NETHER)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_NETHER), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_NETHER)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_NETHER), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_WARPED_NETHER)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));

			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_MYSTIC), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_OAK_MYSTIC)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_MYSTIC), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_SPRUCE_MYSTIC)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_MYSTIC), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BIRCH_MYSTIC)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_MYSTIC), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_JUNGLE_MYSTIC)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_MYSTIC), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_ACACIA_MYSTIC)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_MYSTIC), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_MANGROVE_MYSTIC)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_MYSTIC), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_DARK_OAK_MYSTIC)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_MYSTIC), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_BAMBOO_MYSTIC)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));
			helper.register(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_MYSTIC), new TallDoorItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DramaticDoors.MOD_ID, DDNames.TALL_MACAW_CRIMSON_MYSTIC)), DDItems.conditionalTabProperties("mcwdoors", DramaticDoors.MACAW_TAB)));

		});
	}
}
